# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 941, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cur_genre = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cur_genre.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cur_genre.setFont(font)
        self.cur_genre.setEditable(False)
        self.cur_genre.setObjectName("cur_genre")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.cur_genre.addItem("")
        self.gridLayout.addWidget(self.cur_genre, 1, 0, 1, 1)
        self.time_end = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.time_end.setMinimum(60)
        self.time_end.setMaximum(210)
        self.time_end.setObjectName("time_end")
        self.gridLayout.addWidget(self.time_end, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 5, 1, 3)
        self.findFilms = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.findFilms.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.findFilms.setFont(font)
        self.findFilms.setObjectName("findFilms")
        self.gridLayout.addWidget(self.findFilms, 1, 7, 1, 1)
        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 1, 8, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.add = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 8, 1, 1)
        self.time_start = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.time_start.setMaximum(60)
        self.time_start.setObjectName("time_start")
        self.gridLayout.addWidget(self.time_start, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 2)
        self.name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.name.setEnabled(True)
        self.name.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 5, 1, 2)
        self.year = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.year.setFont(font)
        self.year.setMinimum(1900)
        self.year.setMaximum(2019)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 1, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 941, 701))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.table.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Films"))
        self.cur_genre.setItemText(0, _translate("MainWindow", "Нет"))
        self.cur_genre.setItemText(1, _translate("MainWindow", "Комедия"))
        self.cur_genre.setItemText(2, _translate("MainWindow", "Драма"))
        self.cur_genre.setItemText(3, _translate("MainWindow", "Мелодрама"))
        self.cur_genre.setItemText(4, _translate("MainWindow", "Детектив"))
        self.cur_genre.setItemText(5, _translate("MainWindow", "Документальный"))
        self.cur_genre.setItemText(6, _translate("MainWindow", "Ужасы"))
        self.cur_genre.setItemText(7, _translate("MainWindow", "Музыка"))
        self.cur_genre.setItemText(8, _translate("MainWindow", "Фантастика"))
        self.cur_genre.setItemText(9, _translate("MainWindow", "Анимация"))
        self.cur_genre.setItemText(10, _translate("MainWindow", "Биография"))
        self.cur_genre.setItemText(11, _translate("MainWindow", "Боевик"))
        self.cur_genre.setItemText(12, _translate("MainWindow", "Приключения"))
        self.cur_genre.setItemText(13, _translate("MainWindow", "Война"))
        self.cur_genre.setItemText(14, _translate("MainWindow", "Семейный"))
        self.cur_genre.setItemText(15, _translate("MainWindow", "Триллер"))
        self.cur_genre.setItemText(16, _translate("MainWindow", "Фэнтези"))
        self.cur_genre.setItemText(17, _translate("MainWindow", "Вестерн"))
        self.cur_genre.setItemText(18, _translate("MainWindow", "Мистика"))
        self.cur_genre.setItemText(19, _translate("MainWindow", "Короткометражный"))
        self.cur_genre.setItemText(20, _translate("MainWindow", "Мюзикл"))
        self.cur_genre.setItemText(21, _translate("MainWindow", "Исторический"))
        self.cur_genre.setItemText(22, _translate("MainWindow", "Нуар"))
        self.lineEdit_5.setText(_translate("MainWindow", "Название фильма"))
        self.findFilms.setText(_translate("MainWindow", "Поиск"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.lineEdit.setText(_translate("MainWindow", "Жанр"))
        self.add.setText(_translate("MainWindow", "Добавить фильм"))
        self.lineEdit_2.setText(_translate("MainWindow", "Продолжительность"))
        self.lineEdit_3.setText(_translate("MainWindow", "Год"))
