# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newfilm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 369)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 320, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 371, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.year = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year.setMinimum(1900)
        self.year.setMaximum(2019)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 2, 1, 1, 1)
        self.duration = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.duration.setObjectName("duration")
        self.gridLayout.addWidget(self.duration, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 0, 1, 1)
        self.genre = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.genre.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.genre.setFont(font)
        self.genre.setEditable(False)
        self.genre.setObjectName("genre")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.gridLayout.addWidget(self.genre, 3, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "Название фильма"))
        self.lineEdit_4.setText(_translate("Dialog", "Жанр"))
        self.genre.setItemText(0, _translate("Dialog", "Комедия"))
        self.genre.setItemText(1, _translate("Dialog", "Драма"))
        self.genre.setItemText(2, _translate("Dialog", "Мелодрама"))
        self.genre.setItemText(3, _translate("Dialog", "Детектив"))
        self.genre.setItemText(4, _translate("Dialog", "Документальный"))
        self.genre.setItemText(5, _translate("Dialog", "Ужасы"))
        self.genre.setItemText(6, _translate("Dialog", "Музыка"))
        self.genre.setItemText(7, _translate("Dialog", "Фантастика"))
        self.genre.setItemText(8, _translate("Dialog", "Анимация"))
        self.genre.setItemText(9, _translate("Dialog", "Биография"))
        self.genre.setItemText(10, _translate("Dialog", "Боевик"))
        self.genre.setItemText(11, _translate("Dialog", "Приключения"))
        self.genre.setItemText(12, _translate("Dialog", "Война"))
        self.genre.setItemText(13, _translate("Dialog", "Семейный"))
        self.genre.setItemText(14, _translate("Dialog", "Триллер"))
        self.genre.setItemText(15, _translate("Dialog", "Фэнтези"))
        self.genre.setItemText(16, _translate("Dialog", "Вестерн"))
        self.genre.setItemText(17, _translate("Dialog", "Мистика"))
        self.genre.setItemText(18, _translate("Dialog", "Короткометражный"))
        self.genre.setItemText(19, _translate("Dialog", "Мюзикл"))
        self.genre.setItemText(20, _translate("Dialog", "Исторический"))
        self.genre.setItemText(21, _translate("Dialog", "Нуар"))
        self.lineEdit_6.setText(_translate("Dialog", "Год"))
        self.lineEdit_3.setText(_translate("Dialog", "Продолжительность"))
