# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 395, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_ec = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ec.sizePolicy().hasHeightForWidth())
        self.pushButton_ec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_ec.setFont(font)
        self.pushButton_ec.setStyleSheet("QPushButton {\n"
"background: rgb(149, 149, 149);\n"
"color: rgb(226, 226, 226);\n"
"}")
        self.pushButton_ec.setAutoDefault(False)
        self.pushButton_ec.setDefault(False)
        self.pushButton_ec.setObjectName("pushButton_ec")
        self.gridLayout.addWidget(self.pushButton_ec, 2, 3, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_div.sizePolicy().hasHeightForWidth())
        self.pushButton_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setStyleSheet("QPushButton {\n"
"background:#fa8911;\n"
"border:none;\n"
"}")
        self.pushButton_div.setAutoDefault(False)
        self.pushButton_div.setDefault(False)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 3, 3, 1, 1)
        self.pushButton_ac = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ac.sizePolicy().hasHeightForWidth())
        self.pushButton_ac.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_ac.setFont(font)
        self.pushButton_ac.setStyleSheet("QPushButton {\n"
"background: rgb(149, 149, 149);\n"
"color: rgb(226, 226, 226);\n"
"}")
        self.pushButton_ac.setAutoDefault(False)
        self.pushButton_ac.setDefault(False)
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.gridLayout.addWidget(self.pushButton_ac, 2, 2, 1, 1)
        self.btn_left_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left_2.sizePolicy().hasHeightForWidth())
        self.btn_left_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_left_2.setFont(font)
        self.btn_left_2.setStyleSheet("QPushButton {\n"
"background: rgb(149, 149, 149);\n"
"color: rgb(226, 226, 226);\n"
"}")
        self.btn_left_2.setAutoDefault(False)
        self.btn_left_2.setDefault(False)
        self.btn_left_2.setObjectName("btn_left_2")
        self.gridLayout.addWidget(self.btn_left_2, 2, 0, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n6.sizePolicy().hasHeightForWidth())
        self.pushButton_n6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n6.setFont(font)
        self.pushButton_n6.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n6.setAutoDefault(False)
        self.pushButton_n6.setDefault(False)
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 4, 2, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n3.sizePolicy().hasHeightForWidth())
        self.pushButton_n3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n3.setFont(font)
        self.pushButton_n3.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n3.setAutoDefault(False)
        self.pushButton_n3.setDefault(False)
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 5, 2, 1, 1)
        self.pushButton_n9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n9.sizePolicy().hasHeightForWidth())
        self.pushButton_n9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n9.setFont(font)
        self.pushButton_n9.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n9.setAutoDefault(False)
        self.pushButton_n9.setDefault(False)
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout.addWidget(self.pushButton_n9, 3, 2, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sub.sizePolicy().hasHeightForWidth())
        self.pushButton_sub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setStyleSheet("QPushButton {\n"
"background:#fa8911;\n"
"border:none;\n"
"}")
        self.pushButton_sub.setAutoDefault(False)
        self.pushButton_sub.setDefault(False)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 5, 3, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n4.sizePolicy().hasHeightForWidth())
        self.pushButton_n4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n4.setFont(font)
        self.pushButton_n4.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n4.setAutoDefault(False)
        self.pushButton_n4.setDefault(False)
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 4, 1, 1, 1)
        self.pushButton_n5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n5.sizePolicy().hasHeightForWidth())
        self.pushButton_n5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n5.setFont(font)
        self.pushButton_n5.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n5.setAutoDefault(False)
        self.pushButton_n5.setDefault(False)
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 4, 0, 1, 1)
        self.btn_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right.sizePolicy().hasHeightForWidth())
        self.btn_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_right.setFont(font)
        self.btn_right.setStyleSheet("QPushButton {\n"
"background: rgb(149, 149, 149);\n"
"color: rgb(226, 226, 226);\n"
"}")
        self.btn_right.setAutoDefault(False)
        self.btn_right.setDefault(False)
        self.btn_right.setObjectName("btn_right")
        self.gridLayout.addWidget(self.btn_right, 2, 1, 1, 1)
        self.pushButton_n0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n0.sizePolicy().hasHeightForWidth())
        self.pushButton_n0.setSizePolicy(sizePolicy)
        self.pushButton_n0.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n0.setFont(font)
        self.pushButton_n0.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n0.setAutoDefault(False)
        self.pushButton_n0.setDefault(False)
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout.addWidget(self.pushButton_n0, 6, 0, 1, 1)
        self.pushButton_eq = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eq.sizePolicy().hasHeightForWidth())
        self.pushButton_eq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setStyleSheet("QPushButton {\n"
"background:#fa8911;\n"
"border:none;\n"
"}")
        self.pushButton_eq.setAutoDefault(False)
        self.pushButton_eq.setDefault(False)
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.gridLayout.addWidget(self.pushButton_eq, 6, 2, 1, 1)
        self.pushButton_n1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n1.sizePolicy().hasHeightForWidth())
        self.pushButton_n1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n1.setFont(font)
        self.pushButton_n1.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n1.setAutoDefault(False)
        self.pushButton_n1.setDefault(False)
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 5, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"background:#fa8911;\n"
"border:none;\n"
"}")
        self.pushButton_add.setAutoDefault(False)
        self.pushButton_add.setDefault(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 6, 3, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n2.sizePolicy().hasHeightForWidth())
        self.pushButton_n2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n2.setFont(font)
        self.pushButton_n2.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n2.setAutoDefault(False)
        self.pushButton_n2.setDefault(False)
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 5, 1, 1, 1)
        self.pushButton_n8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n8.sizePolicy().hasHeightForWidth())
        self.pushButton_n8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n8.setFont(font)
        self.pushButton_n8.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n8.setAutoDefault(False)
        self.pushButton_n8.setDefault(False)
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout.addWidget(self.pushButton_n8, 3, 1, 1, 1)
        self.btn_share = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_share.sizePolicy().hasHeightForWidth())
        self.btn_share.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_share.setFont(font)
        self.btn_share.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.btn_share.setAutoDefault(False)
        self.btn_share.setDefault(False)
        self.btn_share.setObjectName("btn_share")
        self.gridLayout.addWidget(self.btn_share, 6, 1, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n7.sizePolicy().hasHeightForWidth())
        self.pushButton_n7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_n7.setFont(font)
        self.pushButton_n7.setStyleSheet("QPushButton {\n"
"    background: #d2d3d7;\n"
"    border:none;\n"
"    color: black;\n"
"}")
        self.pushButton_n7.setAutoDefault(False)
        self.pushButton_n7.setDefault(False)
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 3, 0, 1, 1)
        self.pushButton_mul = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mul.sizePolicy().hasHeightForWidth())
        self.pushButton_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setStyleSheet("QPushButton {\n"
"background:#fa8911;\n"
"border:none;\n"
"}")
        self.pushButton_mul.setAutoDefault(False)
        self.pushButton_mul.setDefault(False)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 4, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(37)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"color:black;\n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"background-color : white;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_ec.setText(_translate("MainWindow", "CE"))
        self.pushButton_ec.setProperty("value", _translate("MainWindow", "prev"))
        self.pushButton_div.setText(_translate("MainWindow", "÷"))
        self.pushButton_div.setProperty("value", _translate("MainWindow", "div"))
        self.pushButton_ac.setText(_translate("MainWindow", "C"))
        self.pushButton_ac.setProperty("value", _translate("MainWindow", "clear"))
        self.btn_left_2.setText(_translate("MainWindow", "("))
        self.btn_left_2.setProperty("value", _translate("MainWindow", "left"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_n6.setProperty("value", _translate("MainWindow", "6"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_n3.setProperty("value", _translate("MainWindow", "3"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_n9.setProperty("value", _translate("MainWindow", "9"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_sub.setProperty("value", _translate("MainWindow", "sub"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_n4.setProperty("value", _translate("MainWindow", "4"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_n5.setProperty("value", _translate("MainWindow", "5"))
        self.btn_right.setText(_translate("MainWindow", ")"))
        self.btn_right.setProperty("value", _translate("MainWindow", "right"))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_n0.setProperty("value", _translate("MainWindow", "0"))
        self.pushButton_eq.setText(_translate("MainWindow", "="))
        self.pushButton_eq.setProperty("value", _translate("MainWindow", "="))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_n1.setProperty("value", _translate("MainWindow", "1"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_add.setProperty("value", _translate("MainWindow", "add"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n2.setProperty("value", _translate("MainWindow", "2"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_n8.setProperty("value", _translate("MainWindow", "8"))
        self.btn_share.setText(_translate("MainWindow", ","))
        self.btn_share.setProperty("value", _translate("MainWindow", ","))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_n7.setProperty("value", _translate("MainWindow", "7"))
        self.pushButton_mul.setText(_translate("MainWindow", "X"))
        self.pushButton_mul.setProperty("value", _translate("MainWindow", "mult"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
